from __future__ import annotations

import json
import struct
import unittest
from pathlib import Path


class PwaAssetTests(unittest.TestCase):
    def test_manifest_declares_install_icons(self) -> None:
        manifest = json.loads(Path("public/manifest.webmanifest").read_text(encoding="utf-8"))
        icon_sources = {icon["src"] for icon in manifest["icons"]}
        self.assertIn("icons/icon-192.png", icon_sources)
        self.assertIn("icons/icon-512.png", icon_sources)
        for source in icon_sources:
            self.assertTrue((Path("public") / source).exists(), source)
        self.assertTrue(Path("public/icons/apple-touch-icon.png").exists())
        self.assertTrue(Path("public/icons/favicon.svg").exists())

    def test_svg_icons_use_centered_gradient_mark(self) -> None:
        icon = Path("public/icons/icon.svg").read_text(encoding="utf-8")
        favicon = Path("public/icons/favicon.svg").read_text(encoding="utf-8")
        self.assertIn('<rect width="512" height="512" rx="112" fill="url(#bg)"', icon)
        self.assertIn('d="M124 166 176 348 256 188 336 348 388 166"', icon)
        self.assertNotIn('fill="#020617"', icon)
        self.assertNotIn('<rect x="56" y="56" width="400" height="400" rx="104" fill="url(#bg)"', icon)
        self.assertNotIn('d="M142 130h148"', icon)
        self.assertNotIn('d="M336 130h34"', icon)
        self.assertIn('<rect width="64" height="64" rx="15" fill="url(#g)"', favicon)
        self.assertNotIn('fill="#020617"', favicon)
        self.assertNotIn('<rect x="7" y="7" width="50" height="50" rx="13" fill="url(#g)"', favicon)
        self.assertIn('d="M15.5 20.75 22 43.5 32 23.5 42 43.5 48.5 20.75"', favicon)

    def test_apple_touch_icon_is_opaque_rgb_png(self) -> None:
        data = Path("public/icons/apple-touch-icon.png").read_bytes()
        self.assertTrue(data.startswith(b"\x89PNG\r\n\x1a\n"))
        ihdr = data[16:29]
        width, height, bit_depth, color_type, compression, filter_method, interlace = struct.unpack(
            ">IIBBBBB", ihdr
        )
        self.assertEqual((180, 180), (width, height))
        self.assertEqual(8, bit_depth)
        self.assertEqual(2, color_type)
        self.assertEqual((0, 0, 0), (compression, filter_method, interlace))

    def test_app_uses_24_hour_browser_time_and_build_versioned_sw(self) -> None:
        app = Path("public/app.js").read_text(encoding="utf-8")
        self.assertIn("hourCycle: 'h23'", app)
        self.assertIn("updateViaCache: 'none'", app)
        self.assertIn("sw.js?v=", app)
        self.assertIn("NOTIFICATIONS_DISABLED_STORAGE_KEY", app)
        self.assertIn("periodic-background-sync", app)
        self.assertIn("registration.periodicSync.register", app)
        self.assertIn("registration.periodicSync.unregister", app)
        self.assertIn("registration.sync.register", app)
        self.assertIn("supportsBackgroundNotifications", app)
        self.assertIn("notificationsDisabledByUser", app)
        self.assertIn("setNotificationsDisabled", app)
        self.assertIn("showUnsupportedNotificationState", app)
        self.assertIn("Notifications unavailable", app)
        self.assertIn("Disable notifications", app)
        self.assertIn("Enable notifications", app)
        self.assertIn("status = await navigator.permissions.query", app)
        self.assertIn("type: 'sync-latest-briefing'", app)
        self.assertIn("const refreshButton = document.querySelector('#refreshButton');", app)
        self.assertIn("REFRESHED_BUILD_STORAGE_KEY", app)
        self.assertIn("function serviceWorkerVersion(buildInfo)", app)
        self.assertIn("buildInfo?.commitSha || buildInfo?.shortSha || buildInfo?.buildId || 'dev'", app)
        self.assertIn("function setupAppUpdateRefresh(registration, buildInfo)", app)
        self.assertIn("const wasControlled = Boolean(navigator.serviceWorker.controller);", app)
        self.assertIn("const hasRefreshedBuild = () => safeSessionStorageGet(REFRESHED_BUILD_STORAGE_KEY) === buildId;", app)
        self.assertIn("registration.addEventListener('updatefound'", app)
        self.assertIn("navigator.serviceWorker.addEventListener('controllerchange'", app)
        self.assertIn("window.location.reload()", app)
        self.assertIn("FALLBACK_TIME_ZONE = 'Europe/Amsterdam'", app)
        self.assertIn("MAX_HEADLINE_LENGTH", app)
        self.assertIn("normalizeBullet", app)
        self.assertIn("temperatureClass", app)
        self.assertIn("primaryUrl", app)
        self.assertIn("bindBriefingBulletLinks", app)
        self.assertIn("data-primary-url", app)
        self.assertIn("role=\"link\"", app)
        self.assertIn("bullet--", app)
        self.assertIn("tag-list", app)
        self.assertIn("sourceIds", app)
        self.assertIn("bindBriefingFilters", app)
        self.assertIn("filterBound", app)
        self.assertIn("renderArchivePicker", app)
        self.assertIn("availableArticleDays", app)
        self.assertIn("loadBriefingSetForDay", app)
        self.assertIn("selectBriefingDay", app)
        self.assertIn("articlePathDayKey", app)
        self.assertIn("briefingPathDayKey", app)
        self.assertIn("date-picker__day", app)
        self.assertIn("todayBriefingView", app)
        self.assertIn("Earlier this morning", app)
        self.assertIn("Earlier this afternoon", app)
        self.assertIn("Earlier this evening", app)

    def test_pwa_merges_earlier_hourly_briefings_into_today_view(self) -> None:
        app = Path("public/app.js").read_text(encoding="utf-8")
        self.assertIn("manifest.briefings", app)
        self.assertIn("loadBriefingSetForDay", app)
        self.assertIn("const remainingCurrentRecords = currentRecords.slice(1);", app)
        self.assertIn("[...remainingCurrentRecords, ...earlierRecords]", app)
        self.assertIn("briefingPathDayKey(path) === dayKey", app)
        self.assertIn("mergeCitations(allBriefings)", app)
        self.assertIn("uniqueBulletRecords(earlierBriefings.flatMap(extractBulletRecords)", app)
        self.assertIn("Today so far", app)
        self.assertIn("!hasSeenItemsForDay(seenState)", app)
        self.assertIn("Latest update", app)
        self.assertIn("Latest retained update", app)
        self.assertIn("recordTimestamp", app)
        self.assertIn("Array.from(recordsByDayPart.entries())", app)
        self.assertIn("latestTimestamp: Math.max(...records.map(recordTimestamp))", app)
        self.assertIn(".sort((left, right) => right.latestTimestamp - left.latestTimestamp)", app)
        self.assertIn("const heroDescription = stripInterestBoilerplate(", app)
        self.assertIn("topBullet?.description || stripLeadingTitle(topBullet?.text, heroTitle) || topBullet?.text || ''", app)
        self.assertIn("heroSummaryEl.textContent = heroDescription || 'No notable updates were found in today’s rolling briefing.';", app)

    def test_briefing_items_open_first_citation_url(self) -> None:
        app = Path("public/app.js").read_text(encoding="utf-8")
        css = Path("public/styles.css").read_text(encoding="utf-8")
        self.assertIn("primaryUrl: firstCitation?.url || ''", app)
        self.assertIn("window.open(url, '_blank', 'noopener,noreferrer')", app)
        self.assertIn("isInteractiveTarget(event.target)", app)
        self.assertIn("keydown", app)
        self.assertIn(".bullet[data-primary-url]", css)
        self.assertIn("cursor: pointer", css)
        self.assertIn(".bullet[data-primary-url]:hover h4", css)
        self.assertIn(".bullet[data-primary-url]:focus-visible h4", css)
        self.assertIn("text-decoration: underline", css)

    def test_hero_headline_links_to_top_article(self) -> None:
        app = Path("public/app.js").read_text(encoding="utf-8")
        css = Path("public/styles.css").read_text(encoding="utf-8")
        self.assertIn("const heroUrl = normalized?.primaryUrl;", app)
        self.assertIn("const link = document.createElement('a');", app)
        self.assertIn("link.href = heroUrl;", app)
        self.assertIn("link.target = '_blank';", app)
        self.assertIn("link.rel = 'noopener noreferrer';", app)
        self.assertIn("link.textContent = heroTitleText;", app)
        self.assertIn("heroHeadlineEl.replaceChildren(link);", app)
        self.assertIn(".hero__content h1 a", css)
        self.assertIn(".hero__content h1 a:hover", css)
        self.assertIn(".hero__content h1 a:focus-visible", css)

    def test_notifications_fall_back_without_background_sync(self) -> None:
        app = Path("public/app.js").read_text(encoding="utf-8")
        self.assertIn("function supportsBackgroundNotifications(registration)", app)
        self.assertIn("'periodicSync' in registration || 'sync' in registration", app)
        self.assertIn("function showUnsupportedNotificationState()", app)
        self.assertIn("notifyButton.disabled = true", app)
        self.assertIn("function notificationButtonText(permission, hasBackgroundNotifications, isDisabled)", app)
        self.assertIn("function updateNotificationButton(permission, hasBackgroundNotifications)", app)
        self.assertIn("notificationsDisabledByUser()", app)
        self.assertIn("const hasBackgroundNotifications = supportsBackgroundNotifications(registration);", app)
        self.assertIn("Notification.permission === 'granted' && !notificationsDisabledByUser() && hasBackgroundNotifications", app)

    def test_background_news_uses_page_icon(self) -> None:
        app = Path("public/app.js").read_text(encoding="utf-8")
        publisher = Path("src/wazzup/publisher.py").read_text(encoding="utf-8")
        self.assertIn("normalizeTemperature", app)
        self.assertIn("normalized.icon === '•'", app)
        self.assertIn("icon: '📄'", app)
        self.assertIn('"icon": "📄"', publisher)

    def test_desktop_sources_card_aligns_with_briefing_card(self) -> None:
        css = Path("public/styles.css").read_text(encoding="utf-8")
        self.assertIn("grid-template-rows: auto 1fr", css)
        self.assertIn("#briefing { grid-row: 1 / span 2; }", css)
        self.assertIn("#sources { grid-row: 2; }", css)

    def test_sidebar_headings_use_compact_scale(self) -> None:
        css = Path("public/styles.css").read_text(encoding="utf-8")
        self.assertIn("#yesterday h2,\n#sources h2", css)
        self.assertIn("font-size: clamp(1.35rem, 2.2vw, 1.8rem)", css)
        self.assertIn("letter-spacing: 0", css)

    def test_source_health_rows_align_status_with_feed_title(self) -> None:
        app = Path("public/app.js").read_text(encoding="utf-8")
        css = Path("public/styles.css").read_text(encoding="utf-8")
        self.assertIn('class="source-item"', app)
        self.assertIn('<div class="source-heading">', app)
        self.assertIn('class="source-filter source-title"', app)
        self.assertIn(".source-item", css)
        self.assertIn(".source-heading", css)
        self.assertIn("justify-content: space-between", css)
        self.assertIn(".source-heading .status", css)

    def test_pwa_tracks_seen_briefing_items_locally(self) -> None:
        app = Path("public/app.js").read_text(encoding="utf-8")
        css = Path("public/styles.css").read_text(encoding="utf-8")
        self.assertIn("const SEEN_BRIEFING_ITEMS_STORAGE_KEY = 'wazzup:seenBriefingItems'", app)
        self.assertIn("const HIDE_SEEN_STORAGE_KEY = 'wazzup:hideSeen'", app)
        self.assertIn("function seenItemStorageKey(dayKey, itemId)", app)
        self.assertIn("manifest?.retentionDays", app)
        self.assertIn("data-seen-item-ids", app)
        self.assertIn("data-seen-state", app)
        self.assertIn("const SEEN_VIEWPORT_LINE_RATIO = 0.25", app)
        self.assertIn("const SCROLL_BOTTOM_EPSILON = 4", app)
        self.assertIn("let pauseSeenScansUntilInput = false", app)
        self.assertIn("function visibleUnreadBullets()", app)
        self.assertIn("function hideSeenIfVisibleSetComplete()", app)
        self.assertIn("function hasBulletPassedSeenLine", app)
        self.assertIn("function isScrolledToBottom", app)
        self.assertIn("let seenLineMatchFound = false", app)
        self.assertIn("scheduleSeenPositionCheck", app)
        self.assertIn("resumeSeenPositionChecksAfterInput", app)
        self.assertIn("if (!hideSeenEnabled || visibleUnreadBullets().length > 0) return;", app)
        self.assertIn("window.addEventListener('scroll', scheduleSeenPositionCheck, { passive: true })", app)
        self.assertIn("window.addEventListener('wheel', resumeSeenPositionChecksAfterInput, { passive: true })", app)
        self.assertIn("window.addEventListener('resize', scheduleSeenPositionCheck)", app)
        self.assertIn("bullet__status--", app)
        self.assertIn("id=\"hideSeenButton\"", app)
        self.assertIn("Hide seen", app)
        self.assertIn("Show seen", app)
        self.assertIn(".bullet--seen", css)
        self.assertIn(".bullet--hidden", css)
        self.assertIn(".bullet--filtered", css)
        self.assertIn(".section--filtered-empty", css)
        self.assertIn("position: absolute", css)
        self.assertIn("top: 1rem", css)
        self.assertIn("right: 1rem", css)
        self.assertIn("padding-right: 5.25rem", css)
        self.assertIn(".bullet__status--new", css)
        self.assertIn(".bullet__status--seen", css)

    def test_reference_links_show_hover_underline(self) -> None:
        css = Path("public/styles.css").read_text(encoding="utf-8")
        self.assertIn(".citation:hover", css)
        self.assertIn(".citation:focus-visible", css)
        self.assertIn("text-decoration: underline", css)
        self.assertIn("text-underline-offset: 0.18em", css)

    def test_briefing_card_header_is_minimal(self) -> None:
        app = Path("public/app.js").read_text(encoding="utf-8")
        css = Path("public/styles.css").read_text(encoding="utf-8")
        self.assertIn('<div class="briefing-header">', app)
        self.assertIn('<p class="meta briefing-meta"><span id="unreadCount">0 unread</span><span class="briefing-meta__generated">Generated ${formatDate(briefing.generatedAt)}</span></p>', app)
        self.assertIn('id="unreadCount"', app)
        self.assertIn("function updateUnreadCount", app)
        self.assertIn("function unreadCountLabel", app)
        self.assertIn('id="filterEmptyState"', app)
        self.assertIn("No articles match this filter.", app)
        self.assertIn("Filtered by", app)
        self.assertIn("data-filter-type=\"category\"", app)
        self.assertIn("data-filter-type=\"source\"", app)
        self.assertIn(".briefing-header", css)
        self.assertIn(".briefing-meta__generated::before", css)
        self.assertIn("align-items: center", css)
        self.assertIn("justify-content: space-between", css)
        self.assertNotIn("Today's rolling briefing", app)
        self.assertNotIn('${escapeHtml(briefing.kind)} briefing', app)
        self.assertNotIn("Window ${formatDate(briefing.windowStart)}", app)
        self.assertRegex(app, r"const\s+hasMultipleSections\s*=\s*\(briefing\.sections\s*\|\|\s*\[\]\)\.length\s*>\s*1;")
        self.assertRegex(app, r"hasMultipleSections\s*\?\s*`<h3>\$\{escapeHtml\(section\.title\)\}</h3>`\s*:\s*''")

    def test_homepage_uses_simple_header_and_yesterday_card(self) -> None:
        html = Path("public/index.html").read_text(encoding="utf-8")
        app = Path("public/app.js").read_text(encoding="utf-8")
        css = Path("public/styles.css").read_text(encoding="utf-8")
        self.assertIn("viewport-fit=cover", html)
        self.assertIn("black-translucent", html)
        self.assertIn('rel="apple-touch-icon" sizes="180x180"', html)
        self.assertIn('id="refreshButton"', html)
        self.assertIn("Refresh available", html)
        self.assertIn("[hidden] { display: none !important; }", css)
        self.assertIn('class="topbar__actions"', html)
        self.assertIn('class="button button--compact button--utility"', html)
        self.assertIn('id="heroMeta"', html)
        self.assertIn("const heroMetaEl = document.querySelector('#heroMeta');", app)
        self.assertIn('<div class="tag-list">', app)
        self.assertIn('<div class="citations">', app)
        self.assertNotIn("topbar__links", html)
        self.assertNotIn("Previous hours", html)
        self.assertIn("id=\"yesterday\"", html)

    def test_archive_date_picker_loads_retained_days_on_demand(self) -> None:
        html = Path("public/index.html").read_text(encoding="utf-8")
        app = Path("public/app.js").read_text(encoding="utf-8")
        css = Path("public/styles.css").read_text(encoding="utf-8")
        self.assertIn("Loading retained dates", html)
        self.assertIn("function availableArticleDays(manifest)", app)
        self.assertIn("(manifest.articles || []).map(articlePathDayKey).filter(Boolean)", app)
        self.assertIn("function retainedDateRange(availableDays)", app)
        self.assertIn("if (!availableDays.length) {\n    yesterdayEl.hidden = true;\n    yesterdayEl.innerHTML = '';", app)
        self.assertIn("yesterdayEl.hidden = false;", app)
        self.assertIn("disabled", app)
        self.assertIn("Choose a retained day to load its articles.", app)
        self.assertIn("async function selectBriefingDay(appState, dayKey)", app)
        self.assertIn("const briefings = await loadBriefingSetForDay", app)
        self.assertNotIn("await renderYesterday(manifest, latest, briefing)", app)
        self.assertIn(".date-picker", css)
        self.assertIn(".date-picker__day:disabled", css)
        self.assertIn("cursor: not-allowed", css)

    def test_safe_area_background_avoids_white_edges(self) -> None:
        html = Path("public/index.html").read_text(encoding="utf-8")
        css = Path("public/styles.css").read_text(encoding="utf-8")
        manifest = json.loads(Path("public/manifest.webmanifest").read_text(encoding="utf-8"))
        self.assertIn('name="theme-color" content="#020617"', html)
        self.assertEqual("#020617", manifest["theme_color"])
        self.assertEqual("#020617", manifest["background_color"])
        self.assertIn("--app-bg-solid: #020617", css)
        self.assertIn("env(safe-area-inset-top", css)
        self.assertIn("overscroll-behavior-y: none", css)
        self.assertIn(".topbar__actions", css)

    def test_footer_contains_repo_commit_and_star_targets(self) -> None:
        html = Path("public/index.html").read_text(encoding="utf-8")
        self.assertIn(
            'rebuilt by <a href="https://github.com/karti001" target="_blank" rel="noopener noreferrer">karti001</a>',
            html,
        )
        self.assertIn("id=\"commitLink\"", html)
        self.assertIn("id=\"starCountText\"", html)
        self.assertIn("https://github.com/DevSecNinja/wazzup", html)

    def test_service_worker_cache_uses_registration_build_id(self) -> None:
        sw = Path("public/sw.js").read_text(encoding="utf-8")
        self.assertIn("searchParams.get('v')", sw)
        self.assertIn("const CACHE_NAME = `wazzup-${BUILD_ID}`", sw)
        self.assertIn("const STATE_CACHE_NAME = 'wazzup-meta'", sw)
        self.assertIn("previous !== null", sw)
        self.assertIn("function formatNotificationBody(headline, summary = '')", sw)
        self.assertIn("const topBullet = briefing.sections?.[0]?.bullets?.[0]", sw)
        self.assertIn("const summary = (topBullet?.description || topBullet?.text || '').trim();", sw)
        self.assertIn("body: formatNotificationBody(briefing.headline, summary)", sw)
        self.assertIn("body: current.body", sw)
        self.assertIn("body: event.data.body || formatNotificationBody(event.data.headline)", sw)
        self.assertIn("event.data?.type !== 'sync-latest-briefing'", sw)
        self.assertIn("self.addEventListener('periodicsync'", sw)
        self.assertIn("self.addEventListener('sync'", sw)
        self.assertIn("self.addEventListener('notificationclick'", sw)

    def test_refresh_button_stays_hidden_after_same_build_reload(self) -> None:
        app = Path("public/app.js").read_text(encoding="utf-8")
        self.assertIn("const hasRefreshedBuild = () => safeSessionStorageGet(REFRESHED_BUILD_STORAGE_KEY) === buildId;", app)
        self.assertIn("const showRefreshButton = (worker) => {\n    if (!isCurrentBuildWorker(worker) || hasRefreshedBuild()) return;", app)
        self.assertIn("if (!isCurrentBuildWorker(navigator.serviceWorker.controller) || hasRefreshedBuild()) return;\n    safeSessionStorageSet(REFRESHED_BUILD_STORAGE_KEY, buildId);", app)

    def test_refresh_button_ignores_obsolete_waiting_service_worker(self) -> None:
        app = Path("public/app.js").read_text(encoding="utf-8")
        self.assertIn("function serviceWorkerScriptVersion(worker)", app)
        self.assertIn("new URL(worker.scriptURL).searchParams.get('v') || ''", app)
        self.assertIn("const isCurrentBuildWorker = (worker) => serviceWorkerScriptVersion(worker) === buildId;", app)
        self.assertIn("const showRefreshButton = (worker) => {\n    if (!isCurrentBuildWorker(worker) || hasRefreshedBuild()) return;", app)
        self.assertIn("if (registration.waiting) showRefreshButton(registration.waiting);", app)
        self.assertIn("if (newWorker.state === 'installed' && navigator.serviceWorker.controller) showRefreshButton(newWorker);", app)
        self.assertIn("if (!isCurrentBuildWorker(navigator.serviceWorker.controller) || hasRefreshedBuild()) return;", app)


if __name__ == "__main__":
    unittest.main()
